apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
specs:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: cbanchio5/auth
